### ISSUE TITLE
Create one headless service for one replica/podgroup

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#173]
**What would you like to be added**:
One headless service should be created for each replica/podgroup

**Why is this needed**:
For large scale workload, there is a limit of the how many pods can be included in the single headless service. And actually we don't need communication for cross replicas

**Completion requirements**:
Potentially provide an API for configuring the headless service

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kannon92** [comment]
/assign

Would it be okay if I take this?

I'll write up a KEP first once I get a good understanding of the code.

**Comment by liurupeng** [comment]
sure, sgtm @kannon92

**Comment by kannon92** [comment]
Does the leader get its own headless service also?

**Comment by liurupeng** [comment]
yes,  leaders will have headless service as well

**Comment by kannon92** [comment]
So the goal of this proposal would be that each group of leader-worker would have their own headless service.

This is because we want leaders to community with workers but we don't need them to communicate with other replicas.

So we have as many headless services as we have replicas?

Sorry if this obvious. I'm trying to understand the difference between Replicas and size.
